#server:
#  ssl:
#    key-store: classpath:4357663_baijianruoli.cn.pfx
#    key-store-type: PKCS12
#    key-store-password: p5fS3Icx
server:
  servlet:
    encoding:
      force-response: true
      force-request: true
spring:
  cache:
    type: redis
  jackson:
    date-format: MM-dd HH:mm
    time-zone: Hongkong
  rabbitmq:
    host: 123.56.129.67
    port: 5672
    username: liqiqi
    password: lldj1234567
    virtual-host: /
  redis:
    host: 123.56.129.67
    port: 6379


